### ISSUE TITLE
Create add endpoint for Infrastructure

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#123]
Make a file in `routes` folder with the name `infrastructure.js`
make a URL as `infrastructure/add` 
this will be a post request with the requirements of the model in `models/infrastructure.js`
also make APIDOC for the same

**Comment by Vikrantsingh22** [comment]
assign this to me

**Comment by Vikrantsingh22** [comment]
I want to work on this issue
