### ISSUE TITLE
eslint runs for all file

### ISSUE THREAD

**Issue by Hitansh159** [tcet-opensource/erp-backend#197]
## Description 📝

eslint runs for all files even for those that are not the part of commit. 

## Steps to Reproduce 🔄

1. `npm run eslint`

## Expected Behavior ✨

it should run for only selected file

## Actual Behavior ❌

It runs for all files. As it sends the file name as the second parameter so it is getting ignored  

## Screenshots 📷

![image](https://github.com/tcet-opensource/erp-backend/assets/65333231/77dbb54c-9d03-4104-aa89-20cdc4ee0db7)

## Environment 🌍

- Operating System: ubantu 20.04
- Browser/Device: NA
- Version/Build: NA

**Comment by rahulsingh2312** [comment]
assign this issue to me
