### ISSUE TITLE
login fails with incorrect error

### ISSUE THREAD

**Issue by Hitansh159** [tcet-opensource/erp-backend#199]
## Description 📝

User login fails with the nonexistent user as 500 saying `"Something is wrong on our side. Try again"`

## Steps to Reproduce 🔄

1. make a post call with incorrect ID

## Expected Behavior ✨

To throw error 500 with saying User doesn't exist

## Actual Behavior ❌

`"Something is wrong on our side. Try again"`

## Screenshots 📷

![image](https://github.com/tcet-opensource/erp-backend/assets/65333231/e9e56be2-df97-4c88-b2cb-30944487c61a)

## Environment 🌍

- Operating System: ubantu 20.04
- Browser/Device: Chrome
- Version/Build: NA

**Comment by Vikrantsingh22** [comment]
I want to work on this
