### ISSUE TITLE
[Feat]: [Create a model for activityBlueprint]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#208]
## Description

Create a ActivityBlueprint model

This model will be named activityBlueprint.js

create a schema with key and value pairs with appropriate conditions.
Models should be added to the model folder.

## Proposed Solution
```
number: int   ENUM: [1..8]  
type: virtual   ENUM: [odd, even]  (set based on number is odd or even)
academicYear: int pattern: 2.*   description: year in which semester started 
startDate: Date
endDate: Date
```

**Comment by skyline-r34v** [comment]
Yo , you can assign this to me ✝️
