### ISSUE TITLE
[Feat]: [Create a model for exam]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#210]
## Description

Create an exam model

This model will be named exam.js

create a schema with key and value pairs with appropriate conditions.
Models should be added to the model folder.

## Proposed Solution
```
date: date
startTime: time
duration: int
supervisor: Faculty 
infrastructure: Infrastructure
course: Course
```

**Comment by Abhishekgoyal007** [comment]
I want to work on this issue
