### ISSUE TITLE
[Feat]: [Create a model for timetable]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#211]
## Description

Create a Timetable model

This model will be named timetable.js

create a schema with key and value pairs with appropriate conditions.
Models should be added to the model folder.

## Proposed Solution
```
startDate: Date
endDate: Date
classIncharge: Faculty 
group: Group
activityBlueprints: ActivityBlueprint[]
lunchbreakStartTime: Time
lunchBreakDuration: int (number of min)
teabreakStartTime: Time
teabreakDuration: int (number of min)
```

**Comment by VinitChawda06** [comment]
I want to work on this Issue

**Comment by TejasNair9977** [comment]
completed in #325
