### ISSUE TITLE
[Feat]: [Create a model for coursework]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#212]
## Description

Create a coursework model

This model will be named coursework.js

create a schema with key and value pairs with appropriate conditions.
Models should be added to the model folder.

## Proposed Solution
```
student: Student
type: str ENUM: [onCampus, offCampus]
course: Course
task: objectID [ref: Practical,  Tutorial, Assignment ]
activity: Activity
marks: int
```

**Comment by sanika-wani** [comment]
assign me this issue
