### ISSUE TITLE
[Feat]: [Create a model for paper]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#213]
## Description

Create a paper model

This model will be named paper.js

create a schema with key and value pairs with appropriate conditions.
Models should be added to the model folder.

## Proposed Solution
```
answerSheetID: longInt
exam: Exam
student: Student
checkedBy: Faculty
mark: int
```

**Comment by ANKIT638-ux** [comment]
Assign me this issue
