### ISSUE TITLE
[Bug]: [Confusing res for validateUser API]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#214]
## Description 📝

Confusing res for validateUser API

## Steps to Reproduce 🔄

1. Validate using incorrect credentials in /auth/validateUser

## Expected Behavior ✨

msg should state unauthorized, or removed

## Actual Behavior ❌

msg states user validated even if unauthorized

## Screenshots 📷

![image](https://github.com/tcet-opensource/erp-backend/assets/85873779/45093d5e-dace-441a-821d-442716c3e1be)

## Environment 🌍

- Operating System: Windows 11
- Version/Build: node version 20.5.0

**Comment by shreyam462** [comment]
interested to work on this issue
