### ISSUE TITLE
[Feat]: [Adding CURD to activityBlueprint]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#215]
## Description

Add CURD to activityBlueprint.js

## Proposed Solution

Use any model with CURD as reference

**Comment by skyline-r34v** [comment]
Yo, assign this me ✝️

**Comment by deepti-50** [comment]
Assign this to me

**Comment by TejasNair9977** [comment]
@deepti-50, Vignesh was already assigned this issue, please try for another one

**Comment by skyline-r34v** [comment]
It's Vighnesh 👀
