### ISSUE TITLE
[Mega-Feat] Create Endpoint for Topic

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#253]
The following tasks need to complete for the endpoint

- [x] #137 
- [x] #206 
- [x] #254
- [ ] #256
- [ ] #255

**Comment by sumitst05** [comment]
Assign this to me

**Comment by Vikrantsingh22** [comment]
I am interested to work on this issue

**Comment by TejasNair9977** [comment]
this mega feat is kinda just gonna be split between multiple people, lets just assume this issue doesnt exist
