### ISSUE TITLE
[Feat] Create all endpoint for tutorials

### ISSUE THREAD

**Issue by Aastha-S-Rai** [tcet-opensource/erp-backend#273]
Make a file in routes folder with the name `tutorial.js`
make a URL as `tutorial/create`, `tutorial/list`, `tutorial/update`, `tutorial/delete`
then make the required files and functions in services and controller folder.
Note: You can refer infrastructure and accreditation for creating endpoints

**Comment by asthasingh182004** [comment]
Assign this to me

**Comment by TejasNair9977** [comment]
completed in #275
