### ISSUE TITLE
[Feat] Write APIDOCs for tutorials

### ISSUE THREAD

**Issue by Aastha-S-Rai** [tcet-opensource/erp-backend#275]
make api doc in `_apidoc.js` for all requests in the route for Tutorial.

**Comment by asthasingh182004** [comment]
Assign this to me

**Comment by TejasNair9977** [comment]
@asthasingh182004 you might have to make the endpoint first, since the apidocs are made for the endpoints. can you do that?

**Comment by asthasingh182004** [comment]
Yess I would love to give it a try
