### ISSUE TITLE
[Feat] Create all endpoint for assignment

### ISSUE THREAD

**Issue by Aastha-S-Rai** [tcet-opensource/erp-backend#277]
Make a file in routes folder with the name `assignment.js`
make a URL as `assignment/create`, `assignment/list`, `assignment/update`, `assignment/delete`
then make the required files and functions in services and controller folder.
Note: You can refer infrastructure and accreditation for creating endpoints

**Comment by hricha11** [comment]
plz assign this to me

**Comment by hricha11** [comment]
Description
added endpoints for assignment and corrected error

Fixes
#277

Checklist
Code follows project's style guidelines.
Changes are documented appropriately.

**Comment by TejasNair9977** [comment]
please dont close issues @hricha11
