### ISSUE TITLE
Change OTP store

### ISSUE THREAD

**Issue by Hitansh159** [tcet-opensource/erp-backend#29]
Currently otp store is just js object. On server reset all the otp will be lost.
If server is not restarted OTP Store will become a big object that will consume a lot of memory. 

Requirement:
1. create OTPStore model 
2. use It in appropriate manner

**Comment by goutham03062001** [comment]
Hey, I would like to work on this issue.

How would you OTP btw, in this project. And is it enough to create a OTP Model ? Or should I implement OTP while signup or signin?
