### ISSUE TITLE
[Feat] Create model for student and add CURD

### ISSUE THREAD

**Issue by kskarthik5** [tcet-opensource/erp-backend#291]
## 1. Create a student model

This model will be named `student.js` within models folder

create a schema with key and value pairs with appropriate conditions.

### Schema
```
ERPID: str
name: str
joiningYear: int 
branch: Department
division: str ENUM: [A, B, C] default: A
rollNo: int
coursesOpted: course[]
```

## 2. Write CURD for student model
create CRUD operations for student model similar to other models

**Comment by swathiharish-gh** [comment]
assign this to me
