### ISSUE TITLE
[Bug]: [Fix Issues with all present testcases]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#303]
## Description 📝

![image](https://github.com/tcet-opensource/erp-backend/assets/85873779/bf1b319d-98ed-4612-bdf4-a012c5107baa)

This is not a valid test case, since the response will always contain something, it has to be validated properly.

Also, some GET requests are being sent as POST requests, for example, the above image, and the below image.

## Expected Behavior ✨

It should at least contain 
```
    expect(response.headers["content-type"]).toMatch(/json/);
    expect(response.status).toBe(200);
    expect(response.body.res).toMatch(/accreditation updated/);
```

## Actual Behavior ❌

Only contains `expect(response.body.res).not.toBeNull();`, which even accepts 404.

![image](https://github.com/tcet-opensource/erp-backend/assets/85873779/ecc2369c-ed72-4e59-ae40-9a8c4957c2d0)

**Comment by sumitst05** [comment]
Assign this issue to me
