### ISSUE TITLE
[Mega-Feat] [Create CRUD, full endpoint for Group, add APIdocs, and also add testcases]

### ISSUE THREAD

**Issue by kskarthik5** [tcet-opensource/erp-backend#314]
## 1. Create all endpoints for Group
Make a file in routes folder with the name `group.js`
make a URL as `group/create`, `group/list`, `group/update`, `group/delete`
then make the required files and functions in services and controller folder.
## 2. Create all testcases for Group
add testcases for all endpoints of group, inside `group.test.js` inside of `test/routes`
## 3. Create APIDOCs for Group
make api doc in `_apidoc.js` for all requests in the route for Group

**Comment by sumitst05** [comment]
Assign this to me
