### ISSUE TITLE
[Mega-Feat]: [Create CRUD, full endpoint for Activity, add APIdocs, and also add testcases]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#315]
## 1. Create CRUD for activity
Create CURD in `models/activity.js` for this model, with reference to other models. Make sure your attributes are correct.

## 2. Create all endpoints for all operations,
Create endpoints for all operations, use Postman for testing if they work. There will need to be a file in `/routes`, `/controller`, `/services`. Create endpoints for `/activity/add` `/activity/update` `/activity/delete/:id` `/activity/list`.

## 3. Create APIdocs for specified endpoint in `_apidoc.js`
Make an entry for it in `_apidoc.js`

## 4. Create testcases for your endpoint
Make a test case for every route that you created inside `/test/routes/activity.test.js`. Take reference from other models while making this.

**Comment by deepti-50** [comment]
Assign this to me
