### ISSUE TITLE
[Mega-Feat]: [Create CRUD, full endpoint for Attendance, add APIdocs, and also add testcases]

### ISSUE THREAD

**Issue by kskarthik5** [tcet-opensource/erp-backend#319]
## 1. Create all endpoints for Attendance
Make a file in routes folder with the name `attendance.js`
make a URL as `attendance/create`, `attendance/list`, `attendance/update`, `attendance/delete`
then make the required files and functions in services and controller folder.
## 2. Create all testcases for Attendance
add testcases for all endpoints of attendance, inside `attendance.test.js` inside of `test/routes`
## 3. Create APIDOCs for Attendance
make api doc in `_apidoc.js` for all requests in the route for Attendance

**Comment by asthasingh182004** [comment]
Assign this to me
