### ISSUE TITLE
[Mega-Feat]: [Create Model, CRUD, full endpoint for Timetable, add APIdocs, and also add testcases]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#320]
## 1. Create Model and CRUD for timetable

Create Model and CURD in `models/timetable.js` for this model, with reference to other models. Make sure your attributes are correct

The attributes for the model are:-
```
startDate: Date
endDate: Date
classIncharge: Faculty  ref
group: Group
activityBlueprints: ActivityBlueprint ref
lunchbreakStartTime: Time
lunchBreakDuration: int (number of min)
teabreakStartTime: Time
teabreakDuration: int (number of min)
```
## 2. Create all endpoints for all operations,
Create endpoints for all operations, use Postman for testing if they work. There will need to be a file in `/routes`, `/controller`, `/services`. Create endpoints for `/timetable/add` `/timetable/update` `/timetable/delete/:id` `/timetable/list`.

## 3. Create APIdocs for specified endpoint in `_apidoc.js`
Make an entry for it in `_apidoc.js`

## 4. Create testcases for your endpoint
Make a test case for every route that you created inside `/test/routes/timetable.test.js`. Take reference from other models while making this.

**Comment by sumitst05** [comment]
Please assign this to me
