### ISSUE TITLE
[Mega-Feat]: [Create Model and CRUD, full endpoint for Notification, add APIdocs, and also add testcases]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#321]
## 1. Create Model and CRUD for notification

Create Model and CURD in `models/notification.js` for this model, with reference to other models. Make sure your attributes are correct

The attributes for the model are:-
```
data: str
title: str
from: ref(Faculty)
type: str ENUM:[”Student”,”Faculty”]
filter: List //stores targeted IDs
```
## 2. Create all endpoints for all operations,
Create endpoints for all operations, use Postman for testing if they work. There will need to be a file in `/routes`, `/controller`, `/services`. Create endpoints for `/notification/add` `/notification/update` `/notification/delete/:id` `/notification/list`.

## 3. Create APIdocs for specified endpoint in `_apidoc.js`
Make an entry for it in `_apidoc.js`

## 4. Create testcases for your endpoint
Make a test case for every route that you created inside `/test/routes/notification.test.js`. Take reference from other models while making this.

**Comment by Aryanzs** [comment]
assign this to me

**Comment by shreyam462** [comment]
i would like to work on this issue
