### ISSUE TITLE
[Mega-Feat]: [Create Endpoint for Adding Attendance (II) , with APIDOCs and testcases]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#354]
The way that this is different from the previous attendance, is that this will be used by teachers, and added in bulk, and the other will be used by the admin. You could add another function in model for inserting many since .save() will not work properly for multiple records. 

You will not have to create a new file for this issue.

## 1. Create all endpoints for all operations,
Create endpoints for all operations, use Postman for testing if they work. There will need to be a modification for file in `/routes`, `/controller`, `/services` and in `app.js`. Create endpoints for `/attendance/add`, `/attendance/list`.

## 2. Create APIdocs for specified endpoint in `_apidoc.js`
Make an entry for it in `_apidoc.js`

## 3. Create testcases for your endpoint
Make a test case for every route that you created inside `/test/routes/attendance.test.js`. Take reference from other models while making this.

**Comment by hricha11** [comment]
plz assign this to me

**Comment by TejasNair9977** [comment]
change of plans
