### ISSUE TITLE
[Feat]: [CRUD and Services for Student Medical History details]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#372]
## Description

The model for student medical history details already exists in the `models/student` folder. We need to add CRUD to this model. Take reference to other models. Create a service that interacts with this model as well, for all 4 operations. Have a look at other services for reference.

**Comment by alifanza259** [comment]
Hello, could you assign this to me ? I would like to contribute on this

**Comment by TejasNair9977** [comment]
Sure! Try to maintain the same structure for services as in the models folder. like just create a folder `student`, and put your service in there. give it the same name as it is in models as well.
