### ISSUE TITLE
create faculty model

### ISSUE THREAD

**Issue by Hitansh159** [tcet-opensource/erp-backend#39]
Create a faculty model

This model will refer to faculty working in college.

create a schema with key and value pairs with appropriate conditions.
Models should be added to the model folder.
the file name should be `faculty.js`

**Comment by sumitshinde-84** [comment]
@Hitansh159 i would like to work on this issue, can you please assign it to me ?

**Comment by zyfrost** [comment]
can i work on the issue#39 about faculty model , can you assign it to me ? @Hitansh159

**Comment by sumitshinde-84** [comment]
Hey @TejasNair9977  , please have a look at my PR #55 which already submitted

**Comment by TejasNair9977** [comment]
Oh, @sumitshinde-84, sorry about that. I'll have a look at it right now.
