### ISSUE TITLE
[woof]: [add husky to the project]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#398]
## Description

the way precommit hooks work right now is pretty awkward, and barely anyone uses it anyway. having that precommit hook work using husky would simplify the process quite a bit. the hook is in `/hooks`.

idea suggested by @Vikrantsingh22 

of course, include eslint and try running every test as well, and make sure all of them pass before being able to fully commit. please also add a format for commit messages.

**Comment by sumitst05** [comment]
assign this to me
