### ISSUE TITLE
[Feat]: [Allotting UIDs to Students and Faculty on add]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#415]
## Description

Right now, we just provide a student a UID, but this should be generated based on what IDs currently exist. The format of an ID for a student is `SCS19124` where `S` stands for student, `CS` stands for the abbreviations of their branch, in this case its `CS`, ie Computer Science/Engineering, `19` is the year which they joined, and `124` is simply a random number provided to them for identification. The format of an ID for a Faculty is `FA0101` where `F` stands for Faculty, and `A0101` is their unique identification, where A can be any letter. It can also be `Z9999`.

## Proposed Solution

First list all student IDs that already exist within a filter of the branch and year of joining, or list all faculty, then simply add one that doesn't exist in the system. Of course, you have to remove UID from the arguments and from wherever the user is providing it, since we will be generating it ourselves.

**Comment by Malay-dev** [comment]
Hey @TejasNair9977, I would like to work on this issue. Please assign it to me...
