### ISSUE TITLE
[Feat]: [Add Validation for Student]

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#430]
## Description

There needs to be validation for all IDs in here. The validation must be done in the controller. You need to provide the service with a proper filter so that it can check if the ID provided in `req.body` actually exists for each collection that it belongs to. For example,
In `req.body` for adding Student, it needs to check that the provided IDs actually exist in the database. As always, never trust that the user is providing valid data.

## Use Case

It will make sure that data given by the user to the database is valid. 

## Proposed Solution

Right before the function that creates the document, check if the IDs provided by the user is valid.

**Comment by ANKIT638-ux** [comment]
Please assign me this issue

**Comment by harsh31dangi** [comment]
Hi @TejasNair9977 , I would like to work on this. Can you assign this to me please?

**Comment by TejasNair9977** [comment]
Sure @harsh31dangi ! Thank you for taking interest in this project!

**Comment by TejasNair9977** [comment]
@harsh31dangi  I'd recommend you to sync your branch and have a look at the new middleware. I'm sure itll make this issue a lot easier to solve!

**Comment by harsh31dangi** [comment]
Yes @TejasNair9977 , I did the code changes according to that, however currently getting some husky error when I try to commit

![image](https://github.com/tcet-opensource/erp-backend/assets/49386972/4a2e3f5b-182d-4c3e-a972-3c41dbb7486f)

Will try to fix that and raise a pull request.
