### ISSUE TITLE
create department model

### ISSUE THREAD

**Issue by TejasNair9977** [tcet-opensource/erp-backend#59]
Create a department model

This model will refer to the department.

create a schema with key and value pairs with appropriate conditions.
Models should be added to the model folder.
the file name should be `department.js`

**Comment by TejasNair9977** [comment]
thank you for your interest! here is the planned schema for department.
```
depId: int
depName: str
yearOfStarting: Date
accreditation: Accreditation         #external ref
infraStructure: Infrastructure         #external ref
courses: Course         #external ref
```
Please let me know if you have any queries on this.

**Comment by TejasNair9977** [comment]
@KAUSTUBHDUBEY790 forgot to ping mb

**Comment by KAUSTUBHDUBEY790** [comment]
@TejasNair9977  assign me the issue i am working on it and also check out the pull i created
